### ISSUE TITLE
feat(wait-for): create a `socialgouv/docker/wait-for` image

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/docker#47]
Based on registry.gitlab.factory.social.gouv.fr/socialgouv/docker/curl
We could use a wait for image to do the basic `initContainers` stuff 

```yaml
  initContainers:
    - name: wait-for-api
      image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/wait-for
      args: 
        - ${API_URL}/api/v1/version
      env:
        # optional
        - name: WAIT_FOR_INTERVAL
          value: 5 # test every 5s
        - name: WAIT_FOR_RETRIES
          value: 120 # = (10min x 60s) / 5s 
```
